name: Publish Package

on:
  push:
    branches:
      - main
    paths: 
      - 'python/ndstorage/_version.py'
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'micro-manager/NDStorage' }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flit
    - name: Install package dependencies
      run: |
        pip install -e .
    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:${{ github.workspace }}/src" >> $GITHUB_ENV
    - name: Debug information
      run: |
        pwd
        ls -R
        echo $PYTHONPATH
        pip list
    - name: Build package
      run: flit build
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
