name: Publish Package

on:
  push:
    branches:
      - main
    paths: 
      - 'python/ndstorage/_version.py'
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'micro-manager/NDTiffStorage' }}
    steps:
    - uses: actions/checkout@v2
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install packaging setuptools twine wheel
    - name: Publish the Python package
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        cd python
        python setup.py sdist bdist_wheel
        twine upload dist/*
