name: Publish Package

on:
  push:
    branches:
      - main
    paths: 
      - 'python/ndstorage/_version.py'
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'micro-manager/NDStorage' }}
    permissions:
      id-token: write  # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flit
    - name: Install package dependencies
      run: |
        cd python
        pip install -e .
    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:${{ github.workspace }}/python" >> $GITHUB_ENV
    - name: Build package
      run: |
        cd python
        flit build
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
